#!/bin/bash

# YOU MUST RUN THIS SCRIPT AS A DIFFERENT USER THAN WHO YOU ARE ENCRYPTING THE HOME DIRECTORY FOR!!!
# AFTER RUNNING WITHOUT ERRORS (REBOOT / TRY AGAIN IF YOU GET A FUSE ERROR), LOGIN AS THE USER YOU
# ENCRYPTED FOR, AND RUN THIS COMMAND, AND BACKUP THE KEY FOR RECOVERY: ecryptfs-unwrap-passphrase

USER_TO_ENCRYPT_HOME_DIR="taoteh1221"

sudo authselect enable-feature with-ecryptfs

sleep 5

sudo usermod -aG ecryptfs $USER_TO_ENCRYPT_HOME_DIR

sleep 5

sudo ecryptfs-migrate-home -u $USER_TO_ENCRYPT_HOME_DIR


